### ISSUE TITLE
page_type not defined -> method_missing error

### ISSUE THREAD

**Issue by jflores1** [cognitelabs/portom-refactor#1]
@davidsilvasmith - hey there, I was trying to build/deploy this site and the build failed with a method_missing error on portom-refactor/source/blog/calendar.html.erb.

I checked the config file and didn't see a helper method anywhere that defined page_type. Is that something you wrote or part of middleman? Trying to figure out how to debug.

Thanks!

Stack Trace:

```
undefined local variable or method `page_type' for #<Middleman::Application:0x70318872774240>
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/middleman-core-3.4.0/lib/middleman-core/configuration.rb:78:in `method_missing'
/Users/jflores1/Sites/portom-refactor/source/blog/calendar-month.html.erb:2:in `block in singletonclass'
/Users/jflores1/Sites/portom-refactor/source/blog/calendar-month.html.erb:65520:in `instance_eval'
/Users/jflores1/Sites/portom-refactor/source/blog/calendar-month.html.erb:65520:in `singletonclass'
/Users/jflores1/Sites/portom-refactor/source/blog/calendar-month.html.erb:65518:in `__tilt_70318840510680'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/rendering.rb:313:in `render_individual_file'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/rendering.rb:181:in `_render_with_all_renderers'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/rendering.rb:149:in `render_template'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/middleman-core-3.4.0/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/jflores1/.rvm/gems/ruby-1.9.3-p194/gems/middleman-core-3.4.0/lib/middleman-core/util.rb:41:in `instrument'
```

**Comment by davidsilvasmith** [comment]
I'll fix it before noon (removing two items from the config will fix it.)

In the meantime you can ignore and deploy anyway (it fails to generate the calendar pages, but no biggie)

No it isn't something I wrote. The calendar generation code is wonky. I tweeted the creator about it and didn't get an answer.

Here is my Stackoverflow question on it.
http://stackoverflow.com/questions/33227668/in-middleman-how-do-i-generate-day-month-and-year-blog-archive-links

**Comment by davidsilvasmith** [comment]
I fixed it and checked it in.

**Comment by jflores1** [comment]
awesome, thank you!!

[image: photo]
_Jesse Flores_
SuperWebPros
517-529-2641 | 713-817-7622 | jesse@superwebpros.com | SuperWebPros.com | 325
East Grand River Ave, Ste. 317, East Lansing, MI 48823
http://linkedin.com/in/jafloresjr  http://twitter.com/jflores1c
Latest Tweet: https://twitter.com/StartupLansing Pitching at @thehatching
https://twitter.com/thehatching soon? #Pitching
https://twitter.com/Pitching to #investors?
https://twitter.com/investors? We've got the 5 slides you MUST have
https://t.co/eD7jX1sabO https://t.co/lrnNRjlNvr Read More
https://twitter.com/StartupLansing/statuses/667130469427904512
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=
